version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-n-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
      - run: 
        name: Auth With NPM
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  tests:
    jobs:
      - test-n-publish
  
          