version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  unit-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
  publish:
    steps:
      - checkout
      - run:
          name: Publish to NPM
          command: | 
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  tests:
    jobs:
      - unit-test
  publish:
    jobs:
      - publish
          